// <auto-generated />
using System;
using BettingApp.Data.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BettingApp.Data.Migrations
{
    [DbContext(typeof(BettingAppContext))]
    [Migration("20190907125653_SecondDataSeed")]
    partial class SecondDataSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BettingApp.Data.Entities.Models.BetType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<string>("Type");

                    b.HasKey("Id");

                    b.ToTable("BetTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Home win",
                            Type = "1"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Away win",
                            Type = "2"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Home win/Tie",
                            Type = "1X"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Away win/Tie",
                            Type = "2X"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Tie",
                            Type = "X"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Home win/Away win",
                            Type = "12"
                        });
                });

            modelBuilder.Entity("BettingApp.Data.Entities.Models.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("EndedAt");

                    b.Property<int>("SportId");

                    b.Property<DateTime>("StartsAt");

                    b.HasKey("Id");

                    b.HasIndex("SportId");

                    b.ToTable("Matches");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndedAt = new DateTime(2019, 9, 7, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            SportId = 1,
                            StartsAt = new DateTime(2019, 9, 7, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            EndedAt = new DateTime(2019, 9, 7, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            SportId = 1,
                            StartsAt = new DateTime(2019, 9, 7, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            EndedAt = new DateTime(2019, 9, 7, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            SportId = 1,
                            StartsAt = new DateTime(2019, 9, 7, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            EndedAt = new DateTime(2019, 9, 7, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            SportId = 1,
                            StartsAt = new DateTime(2019, 9, 7, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            EndedAt = new DateTime(2019, 9, 7, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            SportId = 1,
                            StartsAt = new DateTime(2019, 9, 8, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            EndedAt = new DateTime(2019, 9, 7, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            SportId = 1,
                            StartsAt = new DateTime(2019, 9, 8, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            EndedAt = new DateTime(2019, 9, 7, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            SportId = 1,
                            StartsAt = new DateTime(2019, 9, 9, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            EndedAt = new DateTime(2019, 9, 7, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            SportId = 2,
                            StartsAt = new DateTime(2019, 9, 7, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            EndedAt = new DateTime(2019, 9, 7, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            SportId = 2,
                            StartsAt = new DateTime(2019, 9, 7, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            EndedAt = new DateTime(2019, 9, 7, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            SportId = 2,
                            StartsAt = new DateTime(2019, 9, 7, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            EndedAt = new DateTime(2019, 9, 7, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            SportId = 2,
                            StartsAt = new DateTime(2019, 9, 8, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            EndedAt = new DateTime(2019, 9, 7, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            SportId = 2,
                            StartsAt = new DateTime(2019, 9, 8, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            EndedAt = new DateTime(2019, 9, 7, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            SportId = 2,
                            StartsAt = new DateTime(2019, 9, 9, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14,
                            EndedAt = new DateTime(2019, 9, 7, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            SportId = 3,
                            StartsAt = new DateTime(2019, 9, 7, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 15,
                            EndedAt = new DateTime(2019, 9, 7, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            SportId = 3,
                            StartsAt = new DateTime(2019, 9, 7, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 16,
                            EndedAt = new DateTime(2019, 9, 7, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            SportId = 3,
                            StartsAt = new DateTime(2019, 9, 8, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 17,
                            EndedAt = new DateTime(2019, 9, 7, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            SportId = 3,
                            StartsAt = new DateTime(2019, 9, 8, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 18,
                            EndedAt = new DateTime(2019, 9, 7, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            SportId = 3,
                            StartsAt = new DateTime(2019, 9, 9, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 19,
                            EndedAt = new DateTime(2019, 9, 7, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            SportId = 4,
                            StartsAt = new DateTime(2019, 9, 7, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 20,
                            EndedAt = new DateTime(2019, 9, 7, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            SportId = 4,
                            StartsAt = new DateTime(2019, 9, 7, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 21,
                            EndedAt = new DateTime(2019, 9, 7, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            SportId = 4,
                            StartsAt = new DateTime(2019, 9, 8, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 22,
                            EndedAt = new DateTime(2019, 9, 7, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            SportId = 4,
                            StartsAt = new DateTime(2019, 9, 9, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 23,
                            EndedAt = new DateTime(2019, 9, 7, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            SportId = 5,
                            StartsAt = new DateTime(2019, 9, 7, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 24,
                            EndedAt = new DateTime(2019, 9, 7, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            SportId = 5,
                            StartsAt = new DateTime(2019, 9, 7, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 25,
                            EndedAt = new DateTime(2019, 9, 7, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            SportId = 5,
                            StartsAt = new DateTime(2019, 9, 9, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("BettingApp.Data.Entities.Models.Pair", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BetTypeId");

                    b.Property<bool>("IsTopOffer");

                    b.Property<int>("MatchId");

                    b.Property<double>("Quota");

                    b.Property<string>("Status")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("BetTypeId");

                    b.HasIndex("MatchId");

                    b.ToTable("Pairs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BetTypeId = 1,
                            IsTopOffer = false,
                            MatchId = 1,
                            Quota = 3.7400000000000002,
                            Status = "IsFalse"
                        },
                        new
                        {
                            Id = 2,
                            BetTypeId = 2,
                            IsTopOffer = false,
                            MatchId = 1,
                            Quota = 1.77,
                            Status = "IsCorrect"
                        },
                        new
                        {
                            Id = 3,
                            BetTypeId = 3,
                            IsTopOffer = false,
                            MatchId = 1,
                            Quota = 2.3399999999999999,
                            Status = "IsFalse"
                        },
                        new
                        {
                            Id = 4,
                            BetTypeId = 4,
                            IsTopOffer = false,
                            MatchId = 1,
                            Quota = 2.1400000000000001,
                            Status = "IsCorrect"
                        },
                        new
                        {
                            Id = 5,
                            BetTypeId = 5,
                            IsTopOffer = false,
                            MatchId = 1,
                            Quota = 1.54,
                            Status = "IsFalse"
                        },
                        new
                        {
                            Id = 6,
                            BetTypeId = 6,
                            IsTopOffer = false,
                            MatchId = 1,
                            Quota = 1.24,
                            Status = "IsCorrect"
                        },
                        new
                        {
                            Id = 7,
                            BetTypeId = 1,
                            IsTopOffer = false,
                            MatchId = 2,
                            Quota = 3.7400000000000002,
                            Status = "IsCorrect"
                        },
                        new
                        {
                            Id = 8,
                            BetTypeId = 2,
                            IsTopOffer = false,
                            MatchId = 2,
                            Quota = 1.77,
                            Status = "IsFalse"
                        },
                        new
                        {
                            Id = 9,
                            BetTypeId = 3,
                            IsTopOffer = false,
                            MatchId = 2,
                            Quota = 2.3399999999999999,
                            Status = "IsCorrect"
                        },
                        new
                        {
                            Id = 10,
                            BetTypeId = 4,
                            IsTopOffer = false,
                            MatchId = 2,
                            Quota = 2.1400000000000001,
                            Status = "IsFalse"
                        },
                        new
                        {
                            Id = 11,
                            BetTypeId = 5,
                            IsTopOffer = false,
                            MatchId = 2,
                            Quota = 1.54,
                            Status = "IsFalse"
                        },
                        new
                        {
                            Id = 12,
                            BetTypeId = 6,
                            IsTopOffer = false,
                            MatchId = 2,
                            Quota = 1.24,
                            Status = "IsCorrect"
                        },
                        new
                        {
                            Id = 13,
                            BetTypeId = 1,
                            IsTopOffer = false,
                            MatchId = 3,
                            Quota = 3.7400000000000002,
                            Status = "IsCorrect"
                        },
                        new
                        {
                            Id = 14,
                            BetTypeId = 2,
                            IsTopOffer = false,
                            MatchId = 3,
                            Quota = 1.77,
                            Status = "IsFalse"
                        },
                        new
                        {
                            Id = 15,
                            BetTypeId = 3,
                            IsTopOffer = false,
                            MatchId = 3,
                            Quota = 2.3399999999999999,
                            Status = "IsCorrect"
                        },
                        new
                        {
                            Id = 16,
                            BetTypeId = 4,
                            IsTopOffer = false,
                            MatchId = 3,
                            Quota = 2.1400000000000001,
                            Status = "IsFalse"
                        },
                        new
                        {
                            Id = 17,
                            BetTypeId = 5,
                            IsTopOffer = false,
                            MatchId = 3,
                            Quota = 1.54,
                            Status = "IsFalse"
                        },
                        new
                        {
                            Id = 18,
                            BetTypeId = 6,
                            IsTopOffer = false,
                            MatchId = 3,
                            Quota = 1.24,
                            Status = "IsCorrect"
                        },
                        new
                        {
                            Id = 19,
                            BetTypeId = 1,
                            IsTopOffer = false,
                            MatchId = 4,
                            Quota = 3.7400000000000002,
                            Status = "IsFalse"
                        },
                        new
                        {
                            Id = 20,
                            BetTypeId = 2,
                            IsTopOffer = false,
                            MatchId = 4,
                            Quota = 1.77,
                            Status = "IsFalse"
                        },
                        new
                        {
                            Id = 21,
                            BetTypeId = 3,
                            IsTopOffer = false,
                            MatchId = 4,
                            Quota = 2.3399999999999999,
                            Status = "IsCorrect"
                        },
                        new
                        {
                            Id = 22,
                            BetTypeId = 4,
                            IsTopOffer = false,
                            MatchId = 4,
                            Quota = 2.1400000000000001,
                            Status = "IsCorrect"
                        },
                        new
                        {
                            Id = 23,
                            BetTypeId = 5,
                            IsTopOffer = false,
                            MatchId = 4,
                            Quota = 1.54,
                            Status = "IsCorrect"
                        },
                        new
                        {
                            Id = 24,
                            BetTypeId = 6,
                            IsTopOffer = false,
                            MatchId = 4,
                            Quota = 1.24,
                            Status = "IsFalse"
                        },
                        new
                        {
                            Id = 25,
                            BetTypeId = 1,
                            IsTopOffer = false,
                            MatchId = 5,
                            Quota = 3.7400000000000002,
                            Status = "IsFalse"
                        },
                        new
                        {
                            Id = 26,
                            BetTypeId = 2,
                            IsTopOffer = false,
                            MatchId = 5,
                            Quota = 1.77,
                            Status = "IsCorrect"
                        },
                        new
                        {
                            Id = 27,
                            BetTypeId = 3,
                            IsTopOffer = false,
                            MatchId = 5,
                            Quota = 2.3399999999999999,
                            Status = "IsFalse"
                        },
                        new
                        {
                            Id = 28,
                            BetTypeId = 4,
                            IsTopOffer = false,
                            MatchId = 5,
                            Quota = 2.1400000000000001,
                            Status = "IsCorrect"
                        },
                        new
                        {
                            Id = 29,
                            BetTypeId = 5,
                            IsTopOffer = false,
                            MatchId = 5,
                            Quota = 1.54,
                            Status = "IsFalse"
                        },
                        new
                        {
                            Id = 30,
                            BetTypeId = 6,
                            IsTopOffer = false,
                            MatchId = 5,
                            Quota = 1.24,
                            Status = "IsCorrect"
                        },
                        new
                        {
                            Id = 31,
                            BetTypeId = 1,
                            IsTopOffer = false,
                            MatchId = 6,
                            Quota = 3.7400000000000002,
                            Status = "IsCorrect"
                        },
                        new
                        {
                            Id = 32,
                            BetTypeId = 2,
                            IsTopOffer = false,
                            MatchId = 6,
                            Quota = 1.77,
                            Status = "IsFalse"
                        },
                        new
                        {
                            Id = 33,
                            BetTypeId = 3,
                            IsTopOffer = false,
                            MatchId = 6,
                            Quota = 2.3399999999999999,
                            Status = "IsCorrect"
                        },
                        new
                        {
                            Id = 34,
                            BetTypeId = 4,
                            IsTopOffer = false,
                            MatchId = 6,
                            Quota = 2.1400000000000001,
                            Status = "IsFalse"
                        },
                        new
                        {
                            Id = 35,
                            BetTypeId = 5,
                            IsTopOffer = false,
                            MatchId = 6,
                            Quota = 1.54,
                            Status = "IsFalse"
                        },
                        new
                        {
                            Id = 36,
                            BetTypeId = 6,
                            IsTopOffer = false,
                            MatchId = 6,
                            Quota = 1.24,
                            Status = "IsCorrect"
                        },
                        new
                        {
                            Id = 37,
                            BetTypeId = 1,
                            IsTopOffer = false,
                            MatchId = 7,
                            Quota = 3.7400000000000002,
                            Status = "IsCorrect"
                        },
                        new
                        {
                            Id = 38,
                            BetTypeId = 2,
                            IsTopOffer = false,
                            MatchId = 7,
                            Quota = 1.77,
                            Status = "IsFalse"
                        },
                        new
                        {
                            Id = 39,
                            BetTypeId = 3,
                            IsTopOffer = false,
                            MatchId = 7,
                            Quota = 2.3399999999999999,
                            Status = "IsCorrect"
                        },
                        new
                        {
                            Id = 40,
                            BetTypeId = 4,
                            IsTopOffer = false,
                            MatchId = 7,
                            Quota = 2.1400000000000001,
                            Status = "IsFalse"
                        },
                        new
                        {
                            Id = 41,
                            BetTypeId = 5,
                            IsTopOffer = false,
                            MatchId = 7,
                            Quota = 1.54,
                            Status = "IsFalse"
                        },
                        new
                        {
                            Id = 42,
                            BetTypeId = 6,
                            IsTopOffer = false,
                            MatchId = 7,
                            Quota = 1.24,
                            Status = "IsCorrect"
                        },
                        new
                        {
                            Id = 43,
                            BetTypeId = 1,
                            IsTopOffer = false,
                            MatchId = 8,
                            Quota = 3.7400000000000002,
                            Status = "IsCorrect"
                        },
                        new
                        {
                            Id = 44,
                            BetTypeId = 2,
                            IsTopOffer = false,
                            MatchId = 8,
                            Quota = 1.77,
                            Status = "IsFalse"
                        },
                        new
                        {
                            Id = 45,
                            BetTypeId = 3,
                            IsTopOffer = false,
                            MatchId = 8,
                            Quota = 2.3399999999999999,
                            Status = "IsCorrect"
                        },
                        new
                        {
                            Id = 46,
                            BetTypeId = 4,
                            IsTopOffer = false,
                            MatchId = 8,
                            Quota = 2.1400000000000001,
                            Status = "IsFalse"
                        },
                        new
                        {
                            Id = 47,
                            BetTypeId = 5,
                            IsTopOffer = false,
                            MatchId = 8,
                            Quota = 1.54,
                            Status = "IsFalse"
                        },
                        new
                        {
                            Id = 48,
                            BetTypeId = 1,
                            IsTopOffer = false,
                            MatchId = 9,
                            Quota = 3.7400000000000002,
                            Status = "IsFalse"
                        },
                        new
                        {
                            Id = 49,
                            BetTypeId = 2,
                            IsTopOffer = false,
                            MatchId = 9,
                            Quota = 1.77,
                            Status = "IsCorrect"
                        },
                        new
                        {
                            Id = 50,
                            BetTypeId = 3,
                            IsTopOffer = false,
                            MatchId = 9,
                            Quota = 2.3399999999999999,
                            Status = "IsFalse"
                        },
                        new
                        {
                            Id = 51,
                            BetTypeId = 4,
                            IsTopOffer = false,
                            MatchId = 9,
                            Quota = 2.1400000000000001,
                            Status = "IsCorrect"
                        },
                        new
                        {
                            Id = 52,
                            BetTypeId = 5,
                            IsTopOffer = false,
                            MatchId = 9,
                            Quota = 1.54,
                            Status = "IsFalse"
                        },
                        new
                        {
                            Id = 53,
                            BetTypeId = 1,
                            IsTopOffer = false,
                            MatchId = 10,
                            Quota = 3.7400000000000002,
                            Status = "IsFalse"
                        },
                        new
                        {
                            Id = 54,
                            BetTypeId = 2,
                            IsTopOffer = false,
                            MatchId = 10,
                            Quota = 1.77,
                            Status = "IsCorrect"
                        },
                        new
                        {
                            Id = 55,
                            BetTypeId = 3,
                            IsTopOffer = false,
                            MatchId = 10,
                            Quota = 2.3399999999999999,
                            Status = "IsFalse"
                        },
                        new
                        {
                            Id = 56,
                            BetTypeId = 4,
                            IsTopOffer = false,
                            MatchId = 10,
                            Quota = 2.1400000000000001,
                            Status = "IsCorrect"
                        },
                        new
                        {
                            Id = 57,
                            BetTypeId = 5,
                            IsTopOffer = false,
                            MatchId = 10,
                            Quota = 1.54,
                            Status = "IsFalse"
                        },
                        new
                        {
                            Id = 58,
                            BetTypeId = 1,
                            IsTopOffer = false,
                            MatchId = 11,
                            Quota = 3.7400000000000002,
                            Status = "IsCorrect"
                        },
                        new
                        {
                            Id = 59,
                            BetTypeId = 2,
                            IsTopOffer = false,
                            MatchId = 11,
                            Quota = 1.77,
                            Status = "IsFalse"
                        },
                        new
                        {
                            Id = 60,
                            BetTypeId = 3,
                            IsTopOffer = false,
                            MatchId = 11,
                            Quota = 2.3399999999999999,
                            Status = "IsCorrect"
                        },
                        new
                        {
                            Id = 61,
                            BetTypeId = 4,
                            IsTopOffer = false,
                            MatchId = 11,
                            Quota = 2.1400000000000001,
                            Status = "IsFalse"
                        },
                        new
                        {
                            Id = 62,
                            BetTypeId = 5,
                            IsTopOffer = false,
                            MatchId = 11,
                            Quota = 1.54,
                            Status = "IsFalse"
                        },
                        new
                        {
                            Id = 63,
                            BetTypeId = 1,
                            IsTopOffer = false,
                            MatchId = 12,
                            Quota = 3.7400000000000002,
                            Status = "IsFalse"
                        },
                        new
                        {
                            Id = 64,
                            BetTypeId = 2,
                            IsTopOffer = false,
                            MatchId = 12,
                            Quota = 1.77,
                            Status = "IsCorrect"
                        },
                        new
                        {
                            Id = 65,
                            BetTypeId = 3,
                            IsTopOffer = false,
                            MatchId = 12,
                            Quota = 2.3399999999999999,
                            Status = "IsFalse"
                        },
                        new
                        {
                            Id = 66,
                            BetTypeId = 4,
                            IsTopOffer = false,
                            MatchId = 12,
                            Quota = 2.1400000000000001,
                            Status = "IsCorrect"
                        },
                        new
                        {
                            Id = 67,
                            BetTypeId = 5,
                            IsTopOffer = false,
                            MatchId = 12,
                            Quota = 1.54,
                            Status = "IsFalse"
                        },
                        new
                        {
                            Id = 68,
                            BetTypeId = 1,
                            IsTopOffer = false,
                            MatchId = 13,
                            Quota = 3.7400000000000002,
                            Status = "IsCorrect"
                        },
                        new
                        {
                            Id = 69,
                            BetTypeId = 2,
                            IsTopOffer = false,
                            MatchId = 13,
                            Quota = 1.77,
                            Status = "IsFalse"
                        },
                        new
                        {
                            Id = 70,
                            BetTypeId = 3,
                            IsTopOffer = false,
                            MatchId = 13,
                            Quota = 2.3399999999999999,
                            Status = "IsCorrect"
                        },
                        new
                        {
                            Id = 71,
                            BetTypeId = 4,
                            IsTopOffer = false,
                            MatchId = 13,
                            Quota = 2.1400000000000001,
                            Status = "IsFalse"
                        },
                        new
                        {
                            Id = 72,
                            BetTypeId = 5,
                            IsTopOffer = false,
                            MatchId = 13,
                            Quota = 1.54,
                            Status = "IsFalse"
                        },
                        new
                        {
                            Id = 73,
                            BetTypeId = 6,
                            IsTopOffer = false,
                            MatchId = 13,
                            Quota = 1.24,
                            Status = "IsCorrect"
                        },
                        new
                        {
                            Id = 74,
                            BetTypeId = 1,
                            IsTopOffer = false,
                            MatchId = 14,
                            Quota = 3.7400000000000002,
                            Status = "IsCorrect"
                        },
                        new
                        {
                            Id = 75,
                            BetTypeId = 2,
                            IsTopOffer = false,
                            MatchId = 14,
                            Quota = 1.77,
                            Status = "IsFalse"
                        },
                        new
                        {
                            Id = 76,
                            BetTypeId = 3,
                            IsTopOffer = false,
                            MatchId = 14,
                            Quota = 2.3399999999999999,
                            Status = "IsCorrect"
                        },
                        new
                        {
                            Id = 77,
                            BetTypeId = 4,
                            IsTopOffer = false,
                            MatchId = 14,
                            Quota = 2.1400000000000001,
                            Status = "IsFalse"
                        },
                        new
                        {
                            Id = 78,
                            BetTypeId = 5,
                            IsTopOffer = false,
                            MatchId = 14,
                            Quota = 1.54,
                            Status = "IsFalse"
                        },
                        new
                        {
                            Id = 79,
                            BetTypeId = 6,
                            IsTopOffer = false,
                            MatchId = 14,
                            Quota = 1.24,
                            Status = "IsCorrect"
                        },
                        new
                        {
                            Id = 80,
                            BetTypeId = 1,
                            IsTopOffer = false,
                            MatchId = 15,
                            Quota = 3.7400000000000002,
                            Status = "IsFalse"
                        },
                        new
                        {
                            Id = 81,
                            BetTypeId = 2,
                            IsTopOffer = false,
                            MatchId = 15,
                            Quota = 1.77,
                            Status = "IsCorrect"
                        },
                        new
                        {
                            Id = 82,
                            BetTypeId = 3,
                            IsTopOffer = false,
                            MatchId = 15,
                            Quota = 2.3399999999999999,
                            Status = "IsFalse"
                        },
                        new
                        {
                            Id = 83,
                            BetTypeId = 4,
                            IsTopOffer = false,
                            MatchId = 15,
                            Quota = 2.1400000000000001,
                            Status = "IsCorrect"
                        },
                        new
                        {
                            Id = 84,
                            BetTypeId = 5,
                            IsTopOffer = false,
                            MatchId = 15,
                            Quota = 1.54,
                            Status = "IsFalse"
                        },
                        new
                        {
                            Id = 85,
                            BetTypeId = 6,
                            IsTopOffer = false,
                            MatchId = 15,
                            Quota = 1.24,
                            Status = "IsCorrect"
                        },
                        new
                        {
                            Id = 86,
                            BetTypeId = 1,
                            IsTopOffer = false,
                            MatchId = 16,
                            Quota = 3.7400000000000002,
                            Status = "IsCorrect"
                        },
                        new
                        {
                            Id = 87,
                            BetTypeId = 2,
                            IsTopOffer = false,
                            MatchId = 16,
                            Quota = 1.77,
                            Status = "IsFalse"
                        },
                        new
                        {
                            Id = 88,
                            BetTypeId = 3,
                            IsTopOffer = false,
                            MatchId = 16,
                            Quota = 2.3399999999999999,
                            Status = "IsCorrect"
                        },
                        new
                        {
                            Id = 89,
                            BetTypeId = 4,
                            IsTopOffer = false,
                            MatchId = 16,
                            Quota = 2.1400000000000001,
                            Status = "IsFalse"
                        },
                        new
                        {
                            Id = 90,
                            BetTypeId = 5,
                            IsTopOffer = false,
                            MatchId = 16,
                            Quota = 1.54,
                            Status = "IsFalse"
                        },
                        new
                        {
                            Id = 91,
                            BetTypeId = 6,
                            IsTopOffer = false,
                            MatchId = 16,
                            Quota = 1.24,
                            Status = "IsCorrect"
                        },
                        new
                        {
                            Id = 92,
                            BetTypeId = 1,
                            IsTopOffer = false,
                            MatchId = 17,
                            Quota = 3.7400000000000002,
                            Status = "IsFalse"
                        },
                        new
                        {
                            Id = 93,
                            BetTypeId = 2,
                            IsTopOffer = false,
                            MatchId = 17,
                            Quota = 1.77,
                            Status = "IsCorrect"
                        },
                        new
                        {
                            Id = 94,
                            BetTypeId = 3,
                            IsTopOffer = false,
                            MatchId = 17,
                            Quota = 2.3399999999999999,
                            Status = "IsFalse"
                        },
                        new
                        {
                            Id = 95,
                            BetTypeId = 4,
                            IsTopOffer = false,
                            MatchId = 17,
                            Quota = 2.1400000000000001,
                            Status = "IsCorrect"
                        },
                        new
                        {
                            Id = 96,
                            BetTypeId = 5,
                            IsTopOffer = false,
                            MatchId = 17,
                            Quota = 1.54,
                            Status = "IsFalse"
                        },
                        new
                        {
                            Id = 97,
                            BetTypeId = 6,
                            IsTopOffer = false,
                            MatchId = 17,
                            Quota = 1.24,
                            Status = "IsCorrect"
                        },
                        new
                        {
                            Id = 98,
                            BetTypeId = 1,
                            IsTopOffer = false,
                            MatchId = 18,
                            Quota = 3.7400000000000002,
                            Status = "IsCorrect"
                        },
                        new
                        {
                            Id = 99,
                            BetTypeId = 2,
                            IsTopOffer = false,
                            MatchId = 18,
                            Quota = 1.77,
                            Status = "IsFalse"
                        },
                        new
                        {
                            Id = 100,
                            BetTypeId = 3,
                            IsTopOffer = false,
                            MatchId = 18,
                            Quota = 2.3399999999999999,
                            Status = "IsCorrect"
                        },
                        new
                        {
                            Id = 101,
                            BetTypeId = 4,
                            IsTopOffer = false,
                            MatchId = 18,
                            Quota = 2.1400000000000001,
                            Status = "IsFalse"
                        },
                        new
                        {
                            Id = 102,
                            BetTypeId = 5,
                            IsTopOffer = false,
                            MatchId = 18,
                            Quota = 1.54,
                            Status = "IsFalse"
                        },
                        new
                        {
                            Id = 103,
                            BetTypeId = 6,
                            IsTopOffer = false,
                            MatchId = 18,
                            Quota = 1.24,
                            Status = "IsCorrect"
                        },
                        new
                        {
                            Id = 104,
                            BetTypeId = 1,
                            IsTopOffer = false,
                            MatchId = 19,
                            Quota = 3.7400000000000002,
                            Status = "IsFalse"
                        },
                        new
                        {
                            Id = 105,
                            BetTypeId = 2,
                            IsTopOffer = false,
                            MatchId = 19,
                            Quota = 1.77,
                            Status = "IsCorrect"
                        },
                        new
                        {
                            Id = 106,
                            BetTypeId = 3,
                            IsTopOffer = false,
                            MatchId = 19,
                            Quota = 2.3399999999999999,
                            Status = "IsFalse"
                        },
                        new
                        {
                            Id = 107,
                            BetTypeId = 4,
                            IsTopOffer = false,
                            MatchId = 19,
                            Quota = 2.1400000000000001,
                            Status = "IsCorrect"
                        },
                        new
                        {
                            Id = 108,
                            BetTypeId = 5,
                            IsTopOffer = false,
                            MatchId = 19,
                            Quota = 1.54,
                            Status = "IsFalse"
                        },
                        new
                        {
                            Id = 109,
                            BetTypeId = 6,
                            IsTopOffer = false,
                            MatchId = 19,
                            Quota = 1.24,
                            Status = "IsCorrect"
                        },
                        new
                        {
                            Id = 110,
                            BetTypeId = 1,
                            IsTopOffer = false,
                            MatchId = 20,
                            Quota = 3.7400000000000002,
                            Status = "IsCorrect"
                        },
                        new
                        {
                            Id = 111,
                            BetTypeId = 2,
                            IsTopOffer = false,
                            MatchId = 20,
                            Quota = 1.77,
                            Status = "IsFalse"
                        },
                        new
                        {
                            Id = 112,
                            BetTypeId = 3,
                            IsTopOffer = false,
                            MatchId = 20,
                            Quota = 2.3399999999999999,
                            Status = "IsCorrect"
                        },
                        new
                        {
                            Id = 113,
                            BetTypeId = 4,
                            IsTopOffer = false,
                            MatchId = 20,
                            Quota = 2.1400000000000001,
                            Status = "IsFalse"
                        },
                        new
                        {
                            Id = 114,
                            BetTypeId = 5,
                            IsTopOffer = false,
                            MatchId = 20,
                            Quota = 1.54,
                            Status = "IsFalse"
                        },
                        new
                        {
                            Id = 115,
                            BetTypeId = 6,
                            IsTopOffer = false,
                            MatchId = 20,
                            Quota = 1.24,
                            Status = "IsCorrect"
                        },
                        new
                        {
                            Id = 116,
                            BetTypeId = 1,
                            IsTopOffer = false,
                            MatchId = 21,
                            Quota = 3.7400000000000002,
                            Status = "IsFalse"
                        },
                        new
                        {
                            Id = 117,
                            BetTypeId = 2,
                            IsTopOffer = false,
                            MatchId = 21,
                            Quota = 1.77,
                            Status = "IsCorrect"
                        },
                        new
                        {
                            Id = 118,
                            BetTypeId = 3,
                            IsTopOffer = false,
                            MatchId = 21,
                            Quota = 2.3399999999999999,
                            Status = "IsFalse"
                        },
                        new
                        {
                            Id = 119,
                            BetTypeId = 4,
                            IsTopOffer = false,
                            MatchId = 21,
                            Quota = 2.1400000000000001,
                            Status = "IsCorrect"
                        },
                        new
                        {
                            Id = 120,
                            BetTypeId = 5,
                            IsTopOffer = false,
                            MatchId = 21,
                            Quota = 1.54,
                            Status = "IsFalse"
                        },
                        new
                        {
                            Id = 121,
                            BetTypeId = 6,
                            IsTopOffer = false,
                            MatchId = 21,
                            Quota = 1.24,
                            Status = "IsCorrect"
                        },
                        new
                        {
                            Id = 122,
                            BetTypeId = 1,
                            IsTopOffer = false,
                            MatchId = 22,
                            Quota = 3.7400000000000002,
                            Status = "IsCorrect"
                        },
                        new
                        {
                            Id = 123,
                            BetTypeId = 2,
                            IsTopOffer = false,
                            MatchId = 22,
                            Quota = 1.77,
                            Status = "IsFalse"
                        },
                        new
                        {
                            Id = 124,
                            BetTypeId = 3,
                            IsTopOffer = false,
                            MatchId = 22,
                            Quota = 2.3399999999999999,
                            Status = "IsCorrect"
                        },
                        new
                        {
                            Id = 125,
                            BetTypeId = 4,
                            IsTopOffer = false,
                            MatchId = 22,
                            Quota = 2.1400000000000001,
                            Status = "IsFalse"
                        },
                        new
                        {
                            Id = 126,
                            BetTypeId = 5,
                            IsTopOffer = false,
                            MatchId = 22,
                            Quota = 1.54,
                            Status = "IsFalse"
                        },
                        new
                        {
                            Id = 127,
                            BetTypeId = 6,
                            IsTopOffer = false,
                            MatchId = 22,
                            Quota = 1.24,
                            Status = "IsCorrect"
                        },
                        new
                        {
                            Id = 128,
                            BetTypeId = 1,
                            IsTopOffer = false,
                            MatchId = 23,
                            Quota = 3.7400000000000002,
                            Status = "IsFalse"
                        },
                        new
                        {
                            Id = 129,
                            BetTypeId = 2,
                            IsTopOffer = false,
                            MatchId = 23,
                            Quota = 1.77,
                            Status = "IsCorrect"
                        },
                        new
                        {
                            Id = 130,
                            BetTypeId = 1,
                            IsTopOffer = false,
                            MatchId = 24,
                            Quota = 3.7400000000000002,
                            Status = "IsFalse"
                        },
                        new
                        {
                            Id = 131,
                            BetTypeId = 2,
                            IsTopOffer = false,
                            MatchId = 24,
                            Quota = 1.77,
                            Status = "IsCorrect"
                        },
                        new
                        {
                            Id = 132,
                            BetTypeId = 1,
                            IsTopOffer = false,
                            MatchId = 25,
                            Quota = 3.7400000000000002,
                            Status = "IsFalse"
                        },
                        new
                        {
                            Id = 133,
                            BetTypeId = 2,
                            IsTopOffer = false,
                            MatchId = 25,
                            Quota = 1.77,
                            Status = "IsCorrect"
                        });
                });

            modelBuilder.Entity("BettingApp.Data.Entities.Models.Sport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Sports");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Football"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Basketball"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Handball"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Baseball"
                        },
                        new
                        {
                            Id = 5,
                            Name = "UFC"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Cricket"
                        });
                });

            modelBuilder.Entity("BettingApp.Data.Entities.Models.SportBetType", b =>
                {
                    b.Property<int>("SportId");

                    b.Property<int>("BetTypeId");

                    b.HasKey("SportId", "BetTypeId");

                    b.HasIndex("BetTypeId");

                    b.ToTable("SportBetTypes");

                    b.HasData(
                        new
                        {
                            SportId = 1,
                            BetTypeId = 1
                        },
                        new
                        {
                            SportId = 1,
                            BetTypeId = 2
                        },
                        new
                        {
                            SportId = 1,
                            BetTypeId = 3
                        },
                        new
                        {
                            SportId = 1,
                            BetTypeId = 4
                        },
                        new
                        {
                            SportId = 1,
                            BetTypeId = 5
                        },
                        new
                        {
                            SportId = 1,
                            BetTypeId = 6
                        },
                        new
                        {
                            SportId = 2,
                            BetTypeId = 1
                        },
                        new
                        {
                            SportId = 2,
                            BetTypeId = 2
                        },
                        new
                        {
                            SportId = 2,
                            BetTypeId = 3
                        },
                        new
                        {
                            SportId = 2,
                            BetTypeId = 4
                        },
                        new
                        {
                            SportId = 2,
                            BetTypeId = 5
                        },
                        new
                        {
                            SportId = 3,
                            BetTypeId = 1
                        },
                        new
                        {
                            SportId = 3,
                            BetTypeId = 2
                        },
                        new
                        {
                            SportId = 3,
                            BetTypeId = 3
                        },
                        new
                        {
                            SportId = 3,
                            BetTypeId = 4
                        },
                        new
                        {
                            SportId = 3,
                            BetTypeId = 5
                        },
                        new
                        {
                            SportId = 3,
                            BetTypeId = 6
                        },
                        new
                        {
                            SportId = 4,
                            BetTypeId = 1
                        },
                        new
                        {
                            SportId = 4,
                            BetTypeId = 2
                        },
                        new
                        {
                            SportId = 4,
                            BetTypeId = 3
                        },
                        new
                        {
                            SportId = 4,
                            BetTypeId = 4
                        },
                        new
                        {
                            SportId = 4,
                            BetTypeId = 5
                        },
                        new
                        {
                            SportId = 4,
                            BetTypeId = 6
                        },
                        new
                        {
                            SportId = 5,
                            BetTypeId = 1
                        },
                        new
                        {
                            SportId = 5,
                            BetTypeId = 2
                        },
                        new
                        {
                            SportId = 6,
                            BetTypeId = 1
                        },
                        new
                        {
                            SportId = 6,
                            BetTypeId = 2
                        },
                        new
                        {
                            SportId = 6,
                            BetTypeId = 3
                        },
                        new
                        {
                            SportId = 6,
                            BetTypeId = 4
                        },
                        new
                        {
                            SportId = 6,
                            BetTypeId = 5
                        },
                        new
                        {
                            SportId = 6,
                            BetTypeId = 6
                        });
                });

            modelBuilder.Entity("BettingApp.Data.Entities.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Real Madrid"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Barcelona"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Bayern Munich"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Borussia Dortmund"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Chelsea"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Liverpool"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Leicester"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Manchester City"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Juventus"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Paris Saint-Germain"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Houston Rockets"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Golden State Warriors"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Portland Trail Blazers"
                        },
                        new
                        {
                            Id = 14,
                            Name = "San Antonio Spurs"
                        },
                        new
                        {
                            Id = 15,
                            Name = "LA Clippers"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Denver Nuggets"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Utah Jazz"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Los Angeles Lakers"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Sacramento Kings"
                        },
                        new
                        {
                            Id = 20,
                            Name = "New Orleans Pelicans"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Los Angeles Dodgers"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Pittsburgh Pirates"
                        },
                        new
                        {
                            Id = 23,
                            Name = "New York Yankees"
                        },
                        new
                        {
                            Id = 24,
                            Name = "San Antonio Spurs"
                        },
                        new
                        {
                            Id = 25,
                            Name = "San Francisco Giants"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Boston Red Sox"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Chicago Cubs"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Cincinnati Reds"
                        },
                        new
                        {
                            Id = 29,
                            Name = "St. Louis Cardinals"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Oakland A's"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Jon Jones"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Khabib Nurmagedov"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Henry Cejudo"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Stipe Miocic"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Max Holloway"
                        },
                        new
                        {
                            Id = 36,
                            Name = "Daniel Cormier"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Dustin Poirier"
                        },
                        new
                        {
                            Id = 38,
                            Name = "Kumaru Usman"
                        },
                        new
                        {
                            Id = 39,
                            Name = "Tony Ferguson"
                        },
                        new
                        {
                            Id = 40,
                            Name = "Robert Whittaker"
                        },
                        new
                        {
                            Id = 41,
                            Name = "Croatia"
                        },
                        new
                        {
                            Id = 42,
                            Name = "England"
                        },
                        new
                        {
                            Id = 43,
                            Name = "USA"
                        },
                        new
                        {
                            Id = 44,
                            Name = "France"
                        },
                        new
                        {
                            Id = 45,
                            Name = "Germany"
                        },
                        new
                        {
                            Id = 46,
                            Name = "Brazil"
                        },
                        new
                        {
                            Id = 47,
                            Name = "Spain"
                        },
                        new
                        {
                            Id = 48,
                            Name = "Portugal"
                        },
                        new
                        {
                            Id = 49,
                            Name = "Canada"
                        },
                        new
                        {
                            Id = 50,
                            Name = "Ireland"
                        });
                });

            modelBuilder.Entity("BettingApp.Data.Entities.Models.TeamMatch", b =>
                {
                    b.Property<int>("TeamId");

                    b.Property<int>("MatchId");

                    b.Property<bool>("IsHome");

                    b.Property<int>("Score");

                    b.HasKey("TeamId", "MatchId");

                    b.HasIndex("MatchId");

                    b.ToTable("TeamMatches");

                    b.HasData(
                        new
                        {
                            TeamId = 1,
                            MatchId = 1,
                            IsHome = true,
                            Score = 0
                        },
                        new
                        {
                            TeamId = 2,
                            MatchId = 1,
                            IsHome = false,
                            Score = 1
                        },
                        new
                        {
                            TeamId = 3,
                            MatchId = 2,
                            IsHome = true,
                            Score = 3
                        },
                        new
                        {
                            TeamId = 4,
                            MatchId = 2,
                            IsHome = false,
                            Score = 1
                        },
                        new
                        {
                            TeamId = 5,
                            MatchId = 3,
                            IsHome = true,
                            Score = 2
                        },
                        new
                        {
                            TeamId = 6,
                            MatchId = 3,
                            IsHome = false,
                            Score = 0
                        },
                        new
                        {
                            TeamId = 7,
                            MatchId = 4,
                            IsHome = true,
                            Score = 1
                        },
                        new
                        {
                            TeamId = 8,
                            MatchId = 4,
                            IsHome = false,
                            Score = 1
                        },
                        new
                        {
                            TeamId = 3,
                            MatchId = 5,
                            IsHome = true,
                            Score = 2
                        },
                        new
                        {
                            TeamId = 7,
                            MatchId = 5,
                            IsHome = false,
                            Score = 3
                        },
                        new
                        {
                            TeamId = 2,
                            MatchId = 6,
                            IsHome = true,
                            Score = 2
                        },
                        new
                        {
                            TeamId = 6,
                            MatchId = 6,
                            IsHome = false,
                            Score = 0
                        },
                        new
                        {
                            TeamId = 1,
                            MatchId = 7,
                            IsHome = true,
                            Score = 5
                        },
                        new
                        {
                            TeamId = 8,
                            MatchId = 7,
                            IsHome = false,
                            Score = 3
                        },
                        new
                        {
                            TeamId = 3,
                            MatchId = 8,
                            IsHome = true,
                            Score = 3
                        },
                        new
                        {
                            TeamId = 1,
                            MatchId = 8,
                            IsHome = false,
                            Score = 1
                        },
                        new
                        {
                            TeamId = 14,
                            MatchId = 9,
                            IsHome = true,
                            Score = 20
                        },
                        new
                        {
                            TeamId = 12,
                            MatchId = 9,
                            IsHome = false,
                            Score = 24
                        },
                        new
                        {
                            TeamId = 17,
                            MatchId = 10,
                            IsHome = true,
                            Score = 26
                        },
                        new
                        {
                            TeamId = 18,
                            MatchId = 10,
                            IsHome = false,
                            Score = 33
                        },
                        new
                        {
                            TeamId = 11,
                            MatchId = 11,
                            IsHome = true,
                            Score = 27
                        },
                        new
                        {
                            TeamId = 12,
                            MatchId = 11,
                            IsHome = false,
                            Score = 24
                        },
                        new
                        {
                            TeamId = 15,
                            MatchId = 12,
                            IsHome = true,
                            Score = 18
                        },
                        new
                        {
                            TeamId = 12,
                            MatchId = 12,
                            IsHome = false,
                            Score = 22
                        },
                        new
                        {
                            TeamId = 17,
                            MatchId = 13,
                            IsHome = true,
                            Score = 25
                        },
                        new
                        {
                            TeamId = 18,
                            MatchId = 13,
                            IsHome = false,
                            Score = 17
                        },
                        new
                        {
                            TeamId = 41,
                            MatchId = 14,
                            IsHome = true,
                            Score = 37
                        },
                        new
                        {
                            TeamId = 42,
                            MatchId = 14,
                            IsHome = false,
                            Score = 31
                        },
                        new
                        {
                            TeamId = 43,
                            MatchId = 15,
                            IsHome = true,
                            Score = 27
                        },
                        new
                        {
                            TeamId = 44,
                            MatchId = 15,
                            IsHome = false,
                            Score = 32
                        },
                        new
                        {
                            TeamId = 45,
                            MatchId = 16,
                            IsHome = true,
                            Score = 45
                        },
                        new
                        {
                            TeamId = 46,
                            MatchId = 16,
                            IsHome = false,
                            Score = 35
                        },
                        new
                        {
                            TeamId = 47,
                            MatchId = 17,
                            IsHome = true,
                            Score = 32
                        },
                        new
                        {
                            TeamId = 48,
                            MatchId = 17,
                            IsHome = false,
                            Score = 33
                        },
                        new
                        {
                            TeamId = 49,
                            MatchId = 18,
                            IsHome = true,
                            Score = 26
                        },
                        new
                        {
                            TeamId = 50,
                            MatchId = 18,
                            IsHome = false,
                            Score = 35
                        },
                        new
                        {
                            TeamId = 21,
                            MatchId = 19,
                            IsHome = true,
                            Score = 7
                        },
                        new
                        {
                            TeamId = 22,
                            MatchId = 19,
                            IsHome = false,
                            Score = 9
                        },
                        new
                        {
                            TeamId = 23,
                            MatchId = 20,
                            IsHome = true,
                            Score = 5
                        },
                        new
                        {
                            TeamId = 24,
                            MatchId = 20,
                            IsHome = false,
                            Score = 1
                        },
                        new
                        {
                            TeamId = 25,
                            MatchId = 21,
                            IsHome = true,
                            Score = 0
                        },
                        new
                        {
                            TeamId = 26,
                            MatchId = 21,
                            IsHome = false,
                            Score = 8
                        },
                        new
                        {
                            TeamId = 27,
                            MatchId = 22,
                            IsHome = true,
                            Score = 4
                        },
                        new
                        {
                            TeamId = 28,
                            MatchId = 22,
                            IsHome = false,
                            Score = 1
                        },
                        new
                        {
                            TeamId = 31,
                            MatchId = 23,
                            IsHome = true,
                            Score = 0
                        },
                        new
                        {
                            TeamId = 32,
                            MatchId = 23,
                            IsHome = false,
                            Score = 1
                        },
                        new
                        {
                            TeamId = 33,
                            MatchId = 24,
                            IsHome = true,
                            Score = 0
                        },
                        new
                        {
                            TeamId = 34,
                            MatchId = 24,
                            IsHome = false,
                            Score = 1
                        },
                        new
                        {
                            TeamId = 35,
                            MatchId = 25,
                            IsHome = true,
                            Score = 0
                        },
                        new
                        {
                            TeamId = 36,
                            MatchId = 25,
                            IsHome = false,
                            Score = 1
                        });
                });

            modelBuilder.Entity("BettingApp.Data.Entities.Models.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("IssuedAt");

                    b.Property<double>("MoneyBet");

                    b.Property<string>("Status")
                        .IsRequired();

                    b.Property<double>("TotalQuota");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("BettingApp.Data.Entities.Models.TicketPair", b =>
                {
                    b.Property<int>("TicketId");

                    b.Property<int>("PairId");

                    b.HasKey("TicketId", "PairId");

                    b.HasIndex("PairId");

                    b.ToTable("TicketPairs");
                });

            modelBuilder.Entity("BettingApp.Data.Entities.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("CurrentFunds");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CurrentFunds = 0.0,
                            Username = "MainUser"
                        });
                });

            modelBuilder.Entity("BettingApp.Data.Entities.Models.Match", b =>
                {
                    b.HasOne("BettingApp.Data.Entities.Models.Sport", "Sport")
                        .WithMany("Matches")
                        .HasForeignKey("SportId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BettingApp.Data.Entities.Models.Pair", b =>
                {
                    b.HasOne("BettingApp.Data.Entities.Models.BetType", "BetType")
                        .WithMany("Pairs")
                        .HasForeignKey("BetTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BettingApp.Data.Entities.Models.Match", "Match")
                        .WithMany("Pairs")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BettingApp.Data.Entities.Models.SportBetType", b =>
                {
                    b.HasOne("BettingApp.Data.Entities.Models.BetType", "BetType")
                        .WithMany("SportBetTypes")
                        .HasForeignKey("BetTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BettingApp.Data.Entities.Models.Sport", "Sport")
                        .WithMany("SportBetTypes")
                        .HasForeignKey("SportId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BettingApp.Data.Entities.Models.TeamMatch", b =>
                {
                    b.HasOne("BettingApp.Data.Entities.Models.Match", "Match")
                        .WithMany("TeamMatches")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BettingApp.Data.Entities.Models.Team", "Team")
                        .WithMany("TeamMatches")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BettingApp.Data.Entities.Models.Ticket", b =>
                {
                    b.HasOne("BettingApp.Data.Entities.Models.User", "User")
                        .WithMany("Tickets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BettingApp.Data.Entities.Models.TicketPair", b =>
                {
                    b.HasOne("BettingApp.Data.Entities.Models.Pair", "Pair")
                        .WithMany("TicketPairs")
                        .HasForeignKey("PairId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BettingApp.Data.Entities.Models.Ticket", "Ticket")
                        .WithMany("TicketPairs")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
