// <auto-generated />
using System;
using BettingApp.Data.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BettingApp.Data.Migrations
{
    [DbContext(typeof(BettingAppContext))]
    [Migration("20190920180123_RestructuredDatabase")]
    partial class RestructuredDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BettingApp.Data.Entities.Models.BetOffer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BetTypeId");

                    b.Property<int>("MatchId");

                    b.Property<double>("Quota");

                    b.Property<string>("Status")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("BetTypeId");

                    b.HasIndex("MatchId");

                    b.ToTable("BetOffers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BetTypeId = 1,
                            MatchId = 1,
                            Quota = 3.7400000000000002,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 2,
                            BetTypeId = 2,
                            MatchId = 1,
                            Quota = 1.77,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 3,
                            BetTypeId = 3,
                            MatchId = 1,
                            Quota = 2.3399999999999999,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 4,
                            BetTypeId = 4,
                            MatchId = 1,
                            Quota = 1.54,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 5,
                            BetTypeId = 5,
                            MatchId = 1,
                            Quota = 1.4199999999999999,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 6,
                            BetTypeId = 6,
                            MatchId = 1,
                            Quota = 1.24,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 7,
                            BetTypeId = 1,
                            MatchId = 2,
                            Quota = 3.7400000000000002,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 8,
                            BetTypeId = 2,
                            MatchId = 2,
                            Quota = 1.77,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 9,
                            BetTypeId = 3,
                            MatchId = 2,
                            Quota = 2.3399999999999999,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 10,
                            BetTypeId = 4,
                            MatchId = 2,
                            Quota = 2.1400000000000001,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 11,
                            BetTypeId = 5,
                            MatchId = 2,
                            Quota = 1.4199999999999999,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 12,
                            BetTypeId = 6,
                            MatchId = 2,
                            Quota = 1.24,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 13,
                            BetTypeId = 1,
                            MatchId = 3,
                            Quota = 3.7400000000000002,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 14,
                            BetTypeId = 2,
                            MatchId = 3,
                            Quota = 1.77,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 15,
                            BetTypeId = 3,
                            MatchId = 3,
                            Quota = 2.3399999999999999,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 16,
                            BetTypeId = 4,
                            MatchId = 3,
                            Quota = 2.1400000000000001,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 17,
                            BetTypeId = 5,
                            MatchId = 3,
                            Quota = 1.4199999999999999,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 18,
                            BetTypeId = 6,
                            MatchId = 3,
                            Quota = 1.24,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 19,
                            BetTypeId = 1,
                            MatchId = 4,
                            Quota = 3.7400000000000002,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 20,
                            BetTypeId = 2,
                            MatchId = 4,
                            Quota = 1.77,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 21,
                            BetTypeId = 3,
                            MatchId = 4,
                            Quota = 2.3399999999999999,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 22,
                            BetTypeId = 4,
                            MatchId = 4,
                            Quota = 2.1400000000000001,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 23,
                            BetTypeId = 5,
                            MatchId = 4,
                            Quota = 1.4199999999999999,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 24,
                            BetTypeId = 6,
                            MatchId = 4,
                            Quota = 1.24,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 25,
                            BetTypeId = 1,
                            MatchId = 5,
                            Quota = 3.7400000000000002,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 26,
                            BetTypeId = 2,
                            MatchId = 5,
                            Quota = 1.77,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 27,
                            BetTypeId = 3,
                            MatchId = 5,
                            Quota = 2.3399999999999999,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 28,
                            BetTypeId = 4,
                            MatchId = 5,
                            Quota = 2.1400000000000001,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 29,
                            BetTypeId = 5,
                            MatchId = 5,
                            Quota = 1.4199999999999999,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 30,
                            BetTypeId = 6,
                            MatchId = 5,
                            Quota = 1.24,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 31,
                            BetTypeId = 1,
                            MatchId = 6,
                            Quota = 3.7400000000000002,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 32,
                            BetTypeId = 2,
                            MatchId = 6,
                            Quota = 1.77,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 33,
                            BetTypeId = 3,
                            MatchId = 6,
                            Quota = 2.3399999999999999,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 34,
                            BetTypeId = 4,
                            MatchId = 6,
                            Quota = 2.1400000000000001,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 35,
                            BetTypeId = 5,
                            MatchId = 6,
                            Quota = 1.4199999999999999,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 36,
                            BetTypeId = 6,
                            MatchId = 6,
                            Quota = 1.24,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 37,
                            BetTypeId = 1,
                            MatchId = 7,
                            Quota = 3.7400000000000002,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 38,
                            BetTypeId = 2,
                            MatchId = 7,
                            Quota = 1.77,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 39,
                            BetTypeId = 3,
                            MatchId = 7,
                            Quota = 2.3399999999999999,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 40,
                            BetTypeId = 4,
                            MatchId = 7,
                            Quota = 2.1400000000000001,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 41,
                            BetTypeId = 5,
                            MatchId = 7,
                            Quota = 1.4199999999999999,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 42,
                            BetTypeId = 6,
                            MatchId = 7,
                            Quota = 1.24,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 43,
                            BetTypeId = 1,
                            MatchId = 8,
                            Quota = 3.7400000000000002,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 44,
                            BetTypeId = 2,
                            MatchId = 8,
                            Quota = 1.77,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 45,
                            BetTypeId = 3,
                            MatchId = 8,
                            Quota = 2.3399999999999999,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 46,
                            BetTypeId = 4,
                            MatchId = 8,
                            Quota = 2.1400000000000001,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 47,
                            BetTypeId = 5,
                            MatchId = 8,
                            Quota = 1.4199999999999999,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 48,
                            BetTypeId = 1,
                            MatchId = 9,
                            Quota = 3.7400000000000002,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 49,
                            BetTypeId = 2,
                            MatchId = 9,
                            Quota = 1.77,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 50,
                            BetTypeId = 3,
                            MatchId = 9,
                            Quota = 2.3399999999999999,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 51,
                            BetTypeId = 4,
                            MatchId = 9,
                            Quota = 2.1400000000000001,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 52,
                            BetTypeId = 5,
                            MatchId = 9,
                            Quota = 1.4199999999999999,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 53,
                            BetTypeId = 1,
                            MatchId = 10,
                            Quota = 3.7400000000000002,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 54,
                            BetTypeId = 2,
                            MatchId = 10,
                            Quota = 1.77,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 55,
                            BetTypeId = 3,
                            MatchId = 10,
                            Quota = 2.3399999999999999,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 56,
                            BetTypeId = 4,
                            MatchId = 10,
                            Quota = 2.1400000000000001,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 57,
                            BetTypeId = 5,
                            MatchId = 10,
                            Quota = 1.4199999999999999,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 58,
                            BetTypeId = 1,
                            MatchId = 11,
                            Quota = 3.7400000000000002,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 59,
                            BetTypeId = 2,
                            MatchId = 11,
                            Quota = 1.77,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 60,
                            BetTypeId = 3,
                            MatchId = 11,
                            Quota = 2.3399999999999999,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 61,
                            BetTypeId = 4,
                            MatchId = 11,
                            Quota = 2.1400000000000001,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 62,
                            BetTypeId = 5,
                            MatchId = 11,
                            Quota = 1.4199999999999999,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 63,
                            BetTypeId = 1,
                            MatchId = 12,
                            Quota = 3.7400000000000002,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 64,
                            BetTypeId = 2,
                            MatchId = 12,
                            Quota = 1.77,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 65,
                            BetTypeId = 3,
                            MatchId = 12,
                            Quota = 2.3399999999999999,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 66,
                            BetTypeId = 4,
                            MatchId = 12,
                            Quota = 2.1400000000000001,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 67,
                            BetTypeId = 5,
                            MatchId = 12,
                            Quota = 1.4199999999999999,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 68,
                            BetTypeId = 1,
                            MatchId = 13,
                            Quota = 3.7400000000000002,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 69,
                            BetTypeId = 2,
                            MatchId = 13,
                            Quota = 1.77,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 70,
                            BetTypeId = 3,
                            MatchId = 13,
                            Quota = 2.3399999999999999,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 71,
                            BetTypeId = 4,
                            MatchId = 13,
                            Quota = 2.1400000000000001,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 72,
                            BetTypeId = 5,
                            MatchId = 13,
                            Quota = 1.4199999999999999,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 74,
                            BetTypeId = 1,
                            MatchId = 14,
                            Quota = 3.7400000000000002,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 75,
                            BetTypeId = 2,
                            MatchId = 14,
                            Quota = 1.77,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 76,
                            BetTypeId = 3,
                            MatchId = 14,
                            Quota = 2.3399999999999999,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 77,
                            BetTypeId = 4,
                            MatchId = 14,
                            Quota = 2.1400000000000001,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 79,
                            BetTypeId = 6,
                            MatchId = 14,
                            Quota = 1.24,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 80,
                            BetTypeId = 1,
                            MatchId = 15,
                            Quota = 3.7400000000000002,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 81,
                            BetTypeId = 2,
                            MatchId = 15,
                            Quota = 1.77,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 82,
                            BetTypeId = 3,
                            MatchId = 15,
                            Quota = 2.3399999999999999,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 83,
                            BetTypeId = 4,
                            MatchId = 15,
                            Quota = 2.1400000000000001,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 85,
                            BetTypeId = 6,
                            MatchId = 15,
                            Quota = 1.24,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 86,
                            BetTypeId = 1,
                            MatchId = 16,
                            Quota = 3.7400000000000002,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 87,
                            BetTypeId = 2,
                            MatchId = 16,
                            Quota = 1.77,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 88,
                            BetTypeId = 3,
                            MatchId = 16,
                            Quota = 2.3399999999999999,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 89,
                            BetTypeId = 4,
                            MatchId = 16,
                            Quota = 2.1400000000000001,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 91,
                            BetTypeId = 6,
                            MatchId = 16,
                            Quota = 1.24,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 92,
                            BetTypeId = 1,
                            MatchId = 17,
                            Quota = 3.7400000000000002,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 93,
                            BetTypeId = 2,
                            MatchId = 17,
                            Quota = 1.77,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 94,
                            BetTypeId = 3,
                            MatchId = 17,
                            Quota = 2.3399999999999999,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 95,
                            BetTypeId = 4,
                            MatchId = 17,
                            Quota = 2.1400000000000001,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 97,
                            BetTypeId = 6,
                            MatchId = 17,
                            Quota = 1.24,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 98,
                            BetTypeId = 1,
                            MatchId = 18,
                            Quota = 3.7400000000000002,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 99,
                            BetTypeId = 2,
                            MatchId = 18,
                            Quota = 1.77,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 100,
                            BetTypeId = 3,
                            MatchId = 18,
                            Quota = 2.3399999999999999,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 101,
                            BetTypeId = 4,
                            MatchId = 18,
                            Quota = 2.1400000000000001,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 103,
                            BetTypeId = 6,
                            MatchId = 18,
                            Quota = 1.24,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 104,
                            BetTypeId = 1,
                            MatchId = 19,
                            Quota = 3.7400000000000002,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 105,
                            BetTypeId = 2,
                            MatchId = 19,
                            Quota = 1.77,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 106,
                            BetTypeId = 3,
                            MatchId = 19,
                            Quota = 2.3399999999999999,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 107,
                            BetTypeId = 4,
                            MatchId = 19,
                            Quota = 2.1400000000000001,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 108,
                            BetTypeId = 5,
                            MatchId = 19,
                            Quota = 1.4199999999999999,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 109,
                            BetTypeId = 6,
                            MatchId = 19,
                            Quota = 1.24,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 110,
                            BetTypeId = 1,
                            MatchId = 20,
                            Quota = 3.7400000000000002,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 111,
                            BetTypeId = 2,
                            MatchId = 20,
                            Quota = 1.77,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 112,
                            BetTypeId = 3,
                            MatchId = 20,
                            Quota = 2.3399999999999999,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 113,
                            BetTypeId = 4,
                            MatchId = 20,
                            Quota = 2.1400000000000001,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 114,
                            BetTypeId = 5,
                            MatchId = 20,
                            Quota = 1.4199999999999999,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 115,
                            BetTypeId = 6,
                            MatchId = 20,
                            Quota = 1.24,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 116,
                            BetTypeId = 1,
                            MatchId = 21,
                            Quota = 3.7400000000000002,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 117,
                            BetTypeId = 2,
                            MatchId = 21,
                            Quota = 1.77,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 118,
                            BetTypeId = 3,
                            MatchId = 21,
                            Quota = 2.3399999999999999,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 119,
                            BetTypeId = 4,
                            MatchId = 21,
                            Quota = 2.1400000000000001,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 120,
                            BetTypeId = 5,
                            MatchId = 21,
                            Quota = 1.4199999999999999,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 121,
                            BetTypeId = 6,
                            MatchId = 21,
                            Quota = 1.24,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 122,
                            BetTypeId = 1,
                            MatchId = 22,
                            Quota = 3.7400000000000002,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 123,
                            BetTypeId = 2,
                            MatchId = 22,
                            Quota = 1.77,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 124,
                            BetTypeId = 3,
                            MatchId = 22,
                            Quota = 2.3399999999999999,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 125,
                            BetTypeId = 4,
                            MatchId = 22,
                            Quota = 2.1400000000000001,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 126,
                            BetTypeId = 5,
                            MatchId = 22,
                            Quota = 1.4199999999999999,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 127,
                            BetTypeId = 6,
                            MatchId = 22,
                            Quota = 1.24,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 128,
                            BetTypeId = 1,
                            MatchId = 23,
                            Quota = 3.7400000000000002,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 129,
                            BetTypeId = 2,
                            MatchId = 23,
                            Quota = 1.77,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 130,
                            BetTypeId = 1,
                            MatchId = 24,
                            Quota = 3.7400000000000002,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 131,
                            BetTypeId = 2,
                            MatchId = 24,
                            Quota = 1.77,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 132,
                            BetTypeId = 1,
                            MatchId = 25,
                            Quota = 3.7400000000000002,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 133,
                            BetTypeId = 2,
                            MatchId = 25,
                            Quota = 1.77,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 134,
                            BetTypeId = 1,
                            MatchId = 26,
                            Quota = 4.5,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 135,
                            BetTypeId = 2,
                            MatchId = 26,
                            Quota = 2.21,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 136,
                            BetTypeId = 3,
                            MatchId = 26,
                            Quota = 2.8799999999999999,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 137,
                            BetTypeId = 4,
                            MatchId = 26,
                            Quota = 3.02,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 138,
                            BetTypeId = 5,
                            MatchId = 26,
                            Quota = 1.75,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 139,
                            BetTypeId = 6,
                            MatchId = 26,
                            Quota = 1.54,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 140,
                            BetTypeId = 1,
                            MatchId = 27,
                            Quota = 4.5,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 141,
                            BetTypeId = 2,
                            MatchId = 27,
                            Quota = 2.21,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 142,
                            BetTypeId = 3,
                            MatchId = 27,
                            Quota = 2.8799999999999999,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 143,
                            BetTypeId = 4,
                            MatchId = 27,
                            Quota = 3.02,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 144,
                            BetTypeId = 5,
                            MatchId = 27,
                            Quota = 1.75,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 145,
                            BetTypeId = 6,
                            MatchId = 27,
                            Quota = 1.54,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 146,
                            BetTypeId = 1,
                            MatchId = 28,
                            Quota = 4.5,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 147,
                            BetTypeId = 2,
                            MatchId = 28,
                            Quota = 2.21,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 148,
                            BetTypeId = 3,
                            MatchId = 28,
                            Quota = 2.8799999999999999,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 149,
                            BetTypeId = 4,
                            MatchId = 28,
                            Quota = 3.02,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 150,
                            BetTypeId = 5,
                            MatchId = 28,
                            Quota = 1.75,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 151,
                            BetTypeId = 6,
                            MatchId = 28,
                            Quota = 1.54,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 152,
                            BetTypeId = 1,
                            MatchId = 29,
                            Quota = 4.5,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 153,
                            BetTypeId = 2,
                            MatchId = 29,
                            Quota = 2.21,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 154,
                            BetTypeId = 3,
                            MatchId = 29,
                            Quota = 2.8799999999999999,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 155,
                            BetTypeId = 4,
                            MatchId = 29,
                            Quota = 3.02,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 156,
                            BetTypeId = 5,
                            MatchId = 29,
                            Quota = 1.75,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 157,
                            BetTypeId = 1,
                            MatchId = 30,
                            Quota = 4.5,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 158,
                            BetTypeId = 2,
                            MatchId = 30,
                            Quota = 2.21,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 159,
                            BetTypeId = 3,
                            MatchId = 30,
                            Quota = 2.8799999999999999,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 160,
                            BetTypeId = 4,
                            MatchId = 30,
                            Quota = 3.02,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 161,
                            BetTypeId = 5,
                            MatchId = 30,
                            Quota = 1.75,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 162,
                            BetTypeId = 1,
                            MatchId = 31,
                            Quota = 4.5,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 163,
                            BetTypeId = 2,
                            MatchId = 31,
                            Quota = 2.21,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 164,
                            BetTypeId = 3,
                            MatchId = 31,
                            Quota = 2.8799999999999999,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 165,
                            BetTypeId = 4,
                            MatchId = 31,
                            Quota = 3.02,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 166,
                            BetTypeId = 6,
                            MatchId = 31,
                            Quota = 1.54,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 167,
                            BetTypeId = 1,
                            MatchId = 32,
                            Quota = 4.5,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 168,
                            BetTypeId = 2,
                            MatchId = 32,
                            Quota = 2.21,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 169,
                            BetTypeId = 3,
                            MatchId = 32,
                            Quota = 2.8799999999999999,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 170,
                            BetTypeId = 4,
                            MatchId = 32,
                            Quota = 3.02,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 171,
                            BetTypeId = 5,
                            MatchId = 32,
                            Quota = 1.75,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 172,
                            BetTypeId = 6,
                            MatchId = 32,
                            Quota = 1.4199999999999999,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 173,
                            BetTypeId = 1,
                            MatchId = 33,
                            Quota = 3.7400000000000002,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 174,
                            BetTypeId = 2,
                            MatchId = 33,
                            Quota = 1.77,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 175,
                            BetTypeId = 3,
                            MatchId = 33,
                            Quota = 2.3399999999999999,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 176,
                            BetTypeId = 4,
                            MatchId = 33,
                            Quota = 3.02,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 177,
                            BetTypeId = 5,
                            MatchId = 33,
                            Quota = 1.75,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 178,
                            BetTypeId = 6,
                            MatchId = 33,
                            Quota = 1.54,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 179,
                            BetTypeId = 1,
                            MatchId = 34,
                            Quota = 3.7400000000000002,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 180,
                            BetTypeId = 2,
                            MatchId = 34,
                            Quota = 1.77,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 181,
                            BetTypeId = 3,
                            MatchId = 34,
                            Quota = 2.3399999999999999,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 182,
                            BetTypeId = 4,
                            MatchId = 34,
                            Quota = 3.02,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 183,
                            BetTypeId = 5,
                            MatchId = 34,
                            Quota = 1.75,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 184,
                            BetTypeId = 6,
                            MatchId = 34,
                            Quota = 1.54,
                            Status = "InProgress"
                        });
                });

            modelBuilder.Entity("BettingApp.Data.Entities.Models.BetType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<string>("Type");

                    b.HasKey("Id");

                    b.ToTable("BetTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Home win",
                            Type = "1"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Away win",
                            Type = "2"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Home win/Tie",
                            Type = "1X"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Away win/Tie",
                            Type = "2X"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Tie",
                            Type = "X"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Home win/Away win",
                            Type = "12"
                        });
                });

            modelBuilder.Entity("BettingApp.Data.Entities.Models.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AwayScore");

                    b.Property<int>("AwayTeamId");

                    b.Property<DateTime?>("EndedAt");

                    b.Property<int>("HomeScore");

                    b.Property<int>("HomeTeamId");

                    b.Property<bool>("IsTopOffer");

                    b.Property<int>("SportId");

                    b.Property<DateTime>("StartsAt");

                    b.HasKey("Id");

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("HomeTeamId");

                    b.HasIndex("SportId");

                    b.ToTable("Matches");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AwayScore = 0,
                            AwayTeamId = 2,
                            HomeScore = 0,
                            HomeTeamId = 1,
                            IsTopOffer = false,
                            SportId = 1,
                            StartsAt = new DateTime(2019, 9, 19, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            AwayScore = 0,
                            AwayTeamId = 4,
                            HomeScore = 0,
                            HomeTeamId = 3,
                            IsTopOffer = false,
                            SportId = 1,
                            StartsAt = new DateTime(2019, 9, 19, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            AwayScore = 0,
                            AwayTeamId = 6,
                            HomeScore = 0,
                            HomeTeamId = 5,
                            IsTopOffer = false,
                            SportId = 1,
                            StartsAt = new DateTime(2019, 9, 19, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            AwayScore = 0,
                            AwayTeamId = 8,
                            HomeScore = 0,
                            HomeTeamId = 7,
                            IsTopOffer = false,
                            SportId = 1,
                            StartsAt = new DateTime(2019, 9, 19, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            AwayScore = 0,
                            AwayTeamId = 6,
                            HomeScore = 0,
                            HomeTeamId = 3,
                            IsTopOffer = false,
                            SportId = 1,
                            StartsAt = new DateTime(2019, 9, 20, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            AwayScore = 0,
                            AwayTeamId = 6,
                            HomeScore = 0,
                            HomeTeamId = 2,
                            IsTopOffer = false,
                            SportId = 1,
                            StartsAt = new DateTime(2019, 9, 20, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            AwayScore = 0,
                            AwayTeamId = 8,
                            HomeScore = 0,
                            HomeTeamId = 1,
                            IsTopOffer = false,
                            SportId = 1,
                            StartsAt = new DateTime(2019, 9, 21, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            AwayScore = 0,
                            AwayTeamId = 12,
                            HomeScore = 0,
                            HomeTeamId = 11,
                            IsTopOffer = false,
                            SportId = 2,
                            StartsAt = new DateTime(2019, 9, 19, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            AwayScore = 0,
                            AwayTeamId = 12,
                            HomeScore = 0,
                            HomeTeamId = 14,
                            IsTopOffer = false,
                            SportId = 2,
                            StartsAt = new DateTime(2019, 9, 19, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            AwayScore = 0,
                            AwayTeamId = 18,
                            HomeScore = 0,
                            HomeTeamId = 17,
                            IsTopOffer = false,
                            SportId = 2,
                            StartsAt = new DateTime(2019, 9, 19, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            AwayScore = 0,
                            AwayTeamId = 12,
                            HomeScore = 0,
                            HomeTeamId = 11,
                            IsTopOffer = false,
                            SportId = 2,
                            StartsAt = new DateTime(2019, 9, 20, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            AwayScore = 0,
                            AwayTeamId = 12,
                            HomeScore = 0,
                            HomeTeamId = 15,
                            IsTopOffer = false,
                            SportId = 2,
                            StartsAt = new DateTime(2019, 9, 20, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            AwayScore = 0,
                            AwayTeamId = 18,
                            HomeScore = 0,
                            HomeTeamId = 17,
                            IsTopOffer = false,
                            SportId = 2,
                            StartsAt = new DateTime(2019, 9, 21, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14,
                            AwayScore = 0,
                            AwayTeamId = 42,
                            HomeScore = 0,
                            HomeTeamId = 41,
                            IsTopOffer = false,
                            SportId = 3,
                            StartsAt = new DateTime(2019, 9, 19, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 15,
                            AwayScore = 0,
                            AwayTeamId = 44,
                            HomeScore = 0,
                            HomeTeamId = 43,
                            IsTopOffer = false,
                            SportId = 3,
                            StartsAt = new DateTime(2019, 9, 19, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 16,
                            AwayScore = 0,
                            AwayTeamId = 46,
                            HomeScore = 0,
                            HomeTeamId = 45,
                            IsTopOffer = false,
                            SportId = 3,
                            StartsAt = new DateTime(2019, 9, 20, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 17,
                            AwayScore = 0,
                            AwayTeamId = 48,
                            HomeScore = 0,
                            HomeTeamId = 47,
                            IsTopOffer = false,
                            SportId = 3,
                            StartsAt = new DateTime(2019, 9, 20, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 18,
                            AwayScore = 0,
                            AwayTeamId = 50,
                            HomeScore = 0,
                            HomeTeamId = 49,
                            IsTopOffer = false,
                            SportId = 3,
                            StartsAt = new DateTime(2019, 9, 21, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 19,
                            AwayScore = 0,
                            AwayTeamId = 22,
                            HomeScore = 0,
                            HomeTeamId = 21,
                            IsTopOffer = false,
                            SportId = 4,
                            StartsAt = new DateTime(2019, 9, 19, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 20,
                            AwayScore = 0,
                            AwayTeamId = 24,
                            HomeScore = 0,
                            HomeTeamId = 23,
                            IsTopOffer = false,
                            SportId = 4,
                            StartsAt = new DateTime(2019, 9, 19, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 21,
                            AwayScore = 0,
                            AwayTeamId = 26,
                            HomeScore = 0,
                            HomeTeamId = 25,
                            IsTopOffer = false,
                            SportId = 4,
                            StartsAt = new DateTime(2019, 9, 20, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 22,
                            AwayScore = 0,
                            AwayTeamId = 28,
                            HomeScore = 0,
                            HomeTeamId = 27,
                            IsTopOffer = false,
                            SportId = 4,
                            StartsAt = new DateTime(2019, 9, 21, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 23,
                            AwayScore = 0,
                            AwayTeamId = 32,
                            HomeScore = 0,
                            HomeTeamId = 31,
                            IsTopOffer = false,
                            SportId = 5,
                            StartsAt = new DateTime(2019, 9, 19, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 24,
                            AwayScore = 0,
                            AwayTeamId = 34,
                            HomeScore = 0,
                            HomeTeamId = 33,
                            IsTopOffer = false,
                            SportId = 5,
                            StartsAt = new DateTime(2019, 9, 19, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 25,
                            AwayScore = 0,
                            AwayTeamId = 36,
                            HomeScore = 0,
                            HomeTeamId = 35,
                            IsTopOffer = false,
                            SportId = 5,
                            StartsAt = new DateTime(2019, 9, 21, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 26,
                            AwayScore = 0,
                            AwayTeamId = 2,
                            HomeScore = 0,
                            HomeTeamId = 1,
                            IsTopOffer = true,
                            SportId = 1,
                            StartsAt = new DateTime(2019, 9, 21, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 27,
                            AwayScore = 0,
                            AwayTeamId = 4,
                            HomeScore = 0,
                            HomeTeamId = 3,
                            IsTopOffer = true,
                            SportId = 1,
                            StartsAt = new DateTime(2019, 9, 21, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 28,
                            AwayScore = 0,
                            AwayTeamId = 6,
                            HomeScore = 0,
                            HomeTeamId = 5,
                            IsTopOffer = true,
                            SportId = 1,
                            StartsAt = new DateTime(2019, 9, 21, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 29,
                            AwayScore = 0,
                            AwayTeamId = 41,
                            HomeScore = 0,
                            HomeTeamId = 44,
                            IsTopOffer = true,
                            SportId = 2,
                            StartsAt = new DateTime(2019, 9, 21, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 30,
                            AwayScore = 0,
                            AwayTeamId = 43,
                            HomeScore = 0,
                            HomeTeamId = 42,
                            IsTopOffer = true,
                            SportId = 2,
                            StartsAt = new DateTime(2019, 9, 21, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 31,
                            AwayScore = 0,
                            AwayTeamId = 21,
                            HomeScore = 0,
                            HomeTeamId = 20,
                            IsTopOffer = true,
                            SportId = 3,
                            StartsAt = new DateTime(2019, 9, 21, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 32,
                            AwayScore = 0,
                            AwayTeamId = 31,
                            HomeScore = 0,
                            HomeTeamId = 30,
                            IsTopOffer = true,
                            SportId = 4,
                            StartsAt = new DateTime(2019, 9, 21, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 33,
                            AwayScore = 0,
                            AwayTeamId = 2,
                            HomeScore = 0,
                            HomeTeamId = 1,
                            IsTopOffer = false,
                            SportId = 1,
                            StartsAt = new DateTime(2019, 9, 10, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 34,
                            AwayScore = 0,
                            AwayTeamId = 4,
                            HomeScore = 0,
                            HomeTeamId = 3,
                            IsTopOffer = false,
                            SportId = 1,
                            StartsAt = new DateTime(2019, 9, 10, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("BettingApp.Data.Entities.Models.Sport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Sports");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Football"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Basketball"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Handball"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Baseball"
                        },
                        new
                        {
                            Id = 5,
                            Name = "UFC"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Cricket"
                        });
                });

            modelBuilder.Entity("BettingApp.Data.Entities.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Real Madrid"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Barcelona"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Bayern Munich"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Borussia Dortmund"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Chelsea"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Liverpool"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Leicester"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Manchester City"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Juventus"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Paris Saint-Germain"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Houston Rockets"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Golden State Warriors"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Portland Trail Blazers"
                        },
                        new
                        {
                            Id = 14,
                            Name = "San Antonio Spurs"
                        },
                        new
                        {
                            Id = 15,
                            Name = "LA Clippers"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Denver Nuggets"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Utah Jazz"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Los Angeles Lakers"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Sacramento Kings"
                        },
                        new
                        {
                            Id = 20,
                            Name = "New Orleans Pelicans"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Los Angeles Dodgers"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Pittsburgh Pirates"
                        },
                        new
                        {
                            Id = 23,
                            Name = "New York Yankees"
                        },
                        new
                        {
                            Id = 24,
                            Name = "San Antonio Spurs"
                        },
                        new
                        {
                            Id = 25,
                            Name = "San Francisco Giants"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Boston Red Sox"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Chicago Cubs"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Cincinnati Reds"
                        },
                        new
                        {
                            Id = 29,
                            Name = "St. Louis Cardinals"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Oakland A's"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Jon Jones"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Khabib Nurmagedov"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Henry Cejudo"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Stipe Miocic"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Max Holloway"
                        },
                        new
                        {
                            Id = 36,
                            Name = "Daniel Cormier"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Dustin Poirier"
                        },
                        new
                        {
                            Id = 38,
                            Name = "Kumaru Usman"
                        },
                        new
                        {
                            Id = 39,
                            Name = "Tony Ferguson"
                        },
                        new
                        {
                            Id = 40,
                            Name = "Robert Whittaker"
                        },
                        new
                        {
                            Id = 41,
                            Name = "Croatia"
                        },
                        new
                        {
                            Id = 42,
                            Name = "England"
                        },
                        new
                        {
                            Id = 43,
                            Name = "USA"
                        },
                        new
                        {
                            Id = 44,
                            Name = "France"
                        },
                        new
                        {
                            Id = 45,
                            Name = "Germany"
                        },
                        new
                        {
                            Id = 46,
                            Name = "Brazil"
                        },
                        new
                        {
                            Id = 47,
                            Name = "Spain"
                        },
                        new
                        {
                            Id = 48,
                            Name = "Portugal"
                        },
                        new
                        {
                            Id = 49,
                            Name = "Canada"
                        },
                        new
                        {
                            Id = 50,
                            Name = "Ireland"
                        });
                });

            modelBuilder.Entity("BettingApp.Data.Entities.Models.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("IssuedAt");

                    b.Property<double>("MoneyBet");

                    b.Property<string>("Status")
                        .IsRequired();

                    b.Property<double>("TotalQuota");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("BettingApp.Data.Entities.Models.TicketBetOffer", b =>
                {
                    b.Property<int>("TicketId");

                    b.Property<int>("BetOfferId");

                    b.Property<double>("Quota");

                    b.HasKey("TicketId", "BetOfferId");

                    b.HasIndex("BetOfferId");

                    b.ToTable("TicketBetOffers");
                });

            modelBuilder.Entity("BettingApp.Data.Entities.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("BalanceChange");

                    b.Property<DateTime>("Time");

                    b.Property<int>("TransactionType");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("BettingApp.Data.Entities.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("CurrentFunds");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CurrentFunds = 0.0,
                            Username = "MainUser"
                        });
                });

            modelBuilder.Entity("BettingApp.Data.Entities.Models.BetOffer", b =>
                {
                    b.HasOne("BettingApp.Data.Entities.Models.BetType", "BetType")
                        .WithMany("BetOffers")
                        .HasForeignKey("BetTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BettingApp.Data.Entities.Models.Match", "Match")
                        .WithMany("BetOffers")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BettingApp.Data.Entities.Models.Match", b =>
                {
                    b.HasOne("BettingApp.Data.Entities.Models.Team", "AwayTeam")
                        .WithMany("AwayMatches")
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BettingApp.Data.Entities.Models.Team", "HomeTeam")
                        .WithMany("HomeMatches")
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BettingApp.Data.Entities.Models.Sport", "Sport")
                        .WithMany("Matches")
                        .HasForeignKey("SportId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BettingApp.Data.Entities.Models.Ticket", b =>
                {
                    b.HasOne("BettingApp.Data.Entities.Models.User", "User")
                        .WithMany("Tickets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BettingApp.Data.Entities.Models.TicketBetOffer", b =>
                {
                    b.HasOne("BettingApp.Data.Entities.Models.BetOffer", "BetOffer")
                        .WithMany("TicketBetOffers")
                        .HasForeignKey("BetOfferId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BettingApp.Data.Entities.Models.Ticket", "Ticket")
                        .WithMany("TicketBetOffers")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BettingApp.Data.Entities.Models.Transaction", b =>
                {
                    b.HasOne("BettingApp.Data.Entities.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
